### ISSUE TITLE
Investigate how to setup S3 storage for state

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#1]

**Comment by smacfarlane** [comment]
I've done some tests on how to create/store state in s3 and have posted my findings here:

https://github.alaska.edu/gina/terraform-s3-state-demo

**Comment by teknofire** [comment]
You can also specify a profile to use as part of the aws provider or even a custom credentials file

> provider "aws" {
>   region                   = "us-west-2"
>   shared_credentials_file  = "/Users/tf_user/.aws/creds"
>   profile                  = "customprofile"
> }

**Comment by smacfarlane** [comment]
That works better, I can easily rotate my keys now.  I'd suggest the following:

```
provider "aws" {
  region                   = "us-west-2"
  shared_credentials_file  = "${var.credentials_location}"
  profile                  = "nasa-ace"
}```

That will allow us to define in a `secrets.tfvars` file where the credentials live on a per-user basis without having to modify the plan files.  It looks like `${env.VAR}` support might be on the horizon, so using that when available would clean it up even more.
