### ISSUE TITLE
mobile app attachments improvements

### ISSUE THREAD

**Issue by vlraymond** [gina-alaska/nasa-ace#113]
make sure photos for example store locally with accurate metadata (example location)

**Comment by cstephen** [comment]
I tested whether the app stores GPS coordinates in the EXIF metadata of photos that are submitted. It included some of the EXIF metadata, but not GPS coordinates.

Apparently whether or not an Android device includes GPS coordinates in the photo's EXIF metadata depends on whether the user has chosen this option in their camera app. On my Samsung Galaxy S4 phone it was disabled by default. This appears to be something we have no control over as app developers. You can't force GPS coordinates into the user's photos via the Android Manifest file, for example:

http://stackoverflow.com/questions/38898585/how-to-use-intentmediastore-action-image-capture-and-get-gps-data-in-the-pictu

The ACE mobile app does, of course, capture GPS coordinates separately, which allows us to tie submitted photos and videos to GPS coordinates through LoopBack. The GPS coordinates are just not in the files' own metadata.

The offline photo/video submission problem is covered in a new issue, #115, so I'm going to go ahead and close this one.
