### ISSUE TITLE
Come up with a new domain host to use for the system

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#14]
We talked about this in our last meeting with Joe and Steve for finding a new domain to use for the ACE 2.0 systems.  It looks like we will need to do something as well for the legacy systems until the new system can take it's place.

> The GI is going to let the arsc.edu domain registration expire in August (I think). So we need to re-home https://ace.arsc.edu/ and https://acedev.arsc.edu/. If we can establish new names and configure them on the servers before the expiration, we can have DNS redirect visitors to the new sites before the old domain expires.

**Comment by vlraymond** [comment]
John Walsh looking into this

**Comment by teknofire** [comment]
I'll work with John to get the domain setup and connected with the current instances
