### ISSUE TITLE
Investigate adding facet sort buttons

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#149]
This would be something similar to what is done on https://catalog.data.gov/dataset

![datasets - data gov 2017-03-09 15-14-26](https://cloud.githubusercontent.com/assets/3766/23776519/5a06d4e8-04db-11e7-8419-f2bea684cbe5.png)

**Comment by rwspicer** [comment]
data.gov uses javascript to do it. https://github.com/GSA/ckanext-datagovtheme/blob/ff267d77fcde6d9c0b51044b26d9a000ba4fe8ab/ckanext/datagovtheme/fanstatic_library/scripts/sorting.js
