### ISSUE TITLE
Create copy of current workspace as a new workspace

### ISSUE THREAD

**Issue by BobTorgerson** [gina-alaska/nasa-ace#15]
Steve would like to have the workspace be able to be saved as a duplicate workspace at any point when a user is satisfied with the current map.

**Comment by vlraymond** [comment]
reasons:
new group of users
recreate so as not to duplicate work
operational use - certain location, layers, scale, which are common to a lot of different events... use as  a template

**Comment by vlraymond** [comment]
replaced with views functionality. Closing for now
