### ISSUE TITLE
Ability to take all currently active layers and open a new view in a workspace with those layers active

### ISSUE THREAD

**Issue by BobTorgerson** [gina-alaska/nasa-ace#25]
Steve would like to see an ability to take all currently active layers and create a new view (3D or 2D view) and have all active layers that will re-project properly shown on the new view.

**Comment by grimm** [comment]
Only prompt for view name, copy current view settings with only active layers to new view.

Use new action called copy/duplicate.   Action should create new view with current view info and then pass the user to the new view's edit form.
