### ISSUE TITLE
Make private datasets accessible to members of a group

### ISSUE THREAD

**Issue by BobTorgerson** [gina-alaska/nasa-ace#33]
Allow for organizations to provide their private datasets to groups, making the group permissions overriding the organization's permissions.

**Comment by teknofire** [comment]
Outcome from this should be a proposal to determine the future development on how this will be implemented.

**Comment by BobTorgerson** [comment]
A great example of overriding authorizations is given here: http://docs.ckan.org/en/latest/extensions/tutorial.html#implementing-the-iauthfunctions-plugin-interface
