### ISSUE TITLE
Identify purpose of image carousel

### ISSUE THREAD

**Issue by tomheinrichs** [gina-alaska/nasa-ace#41]

**Comment by tomheinrichs** [comment]
Images will be captioned. Need to decide goal of what is presented in carousel so can make intelligent selection of images.

**Comment by vlraymond** [comment]
no caption for images, one statement and logo that goes over all photos.

VR to re-size photos to 1140 x 400 and share out to JG

**Comment by vlraymond** [comment]
carousel text:
The Arctic Collaborative Environment promotes understanding and decision-support through data sharing and visualization in a web-based, open-access, environmentally-focused research system

cropped images (let me know - are these high enough resolution? I feel like UAF photo dept. sent lower res than we may need) are in https://drive.google.com/drive/u/1/folders/0BwrPnZCuq3CLODA2emMzb3hwdU0
