### ISSUE TITLE
Add a method to restrict access for creating tags

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#51]

**Comment by teknofire** [comment]
This does not look to be easy to implement without overriding a bunch of internal CKAN functionality.

**Comment by teknofire** [comment]
Lets take a look at changing the tag form to be a drop down pick list for tags that operates like the organization list.  

It should allow the user to enter text to create a new tag.

**Comment by BobTorgerson** [comment]
http://docs.ckan.org/en/latest/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IDatasetForm
