### ISSUE TITLE
Updating icons for the categories on the home page

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#54]

**Comment by vlraymond** [comment]
https://drive.google.com/drive/u/1/folders/0BwrPnZCuq3CLb2stakRTMVh5elU some icons today made using Noun Project entities. These fall into the categories JW has identified

**Comment by vlraymond** [comment]
https://drive.google.com/drive/u/1/folders/0BwrPnZCuq3CLUE1zQjJ6dFlKeVk latest and greatest icon set lives ^

**Comment by vlraymond** [comment]
https://drive.google.com/drive/u/1/folders/0BwrPnZCuq3CLUE1zQjJ6dFlKeVk < latest icon set

**Comment by vlraymond** [comment]
updated and created pull request for this issue
