### ISSUE TITLE
Base cookbook for managing AWS systems

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#7]
Things like dns/ntp/etc... for base server configuration

**Comment by smacfarlane** [comment]
http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Networking.html

Some good reading on how to configure the networking essentials inside a VPC

**Comment by smacfarlane** [comment]
I think we will want to go hands-off on DNS, NTP as long as we are using the Amazon provided AMIs and until we have a better understanding of running servers in  AWS with custom AMIs
