### ISSUE TITLE
Mobile app: Harden LoopBack ACLs without breaking functionality

### ISSUE THREAD

**Issue by cstephen** [gina-alaska/nasa-ace#71]
Creating and modifying user accounts should be restricted to the admin user, but I discovered that overzealously locking operations down to the admin user breaks the LoopBack server/client sync functionality. We need to determine what should and what should not be restricted to the admin user in the LoopBack ACLs.

**Comment by teknofire** [comment]
@cstephen Is #101 a duplicate of this issue?

**Comment by cstephen** [comment]
They're similar enough that we should close one of them. I'll go ahead and close this because the other one is more specific.
