### ISSUE TITLE
Update permissions to allow any users to create organizations and groups

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/nasa-ace#92]

**Comment by BobTorgerson** [comment]
This is a simple change to the template configuration file for CKAN: 

ckan.auth.user_create_groups = false
ckan.auth.user_create_organizations = false

I'm making this change now and will push it to the Github for nace-ckan.

**Comment by BobTorgerson** [comment]
Change made and uploaded to the https://github.alaska.edu/gina-cookbooks/nace-ckan cookbook. This has not yet been uploaded to the Chef server to allow for wider review.

**Comment by teknofire** [comment]
@BobTorgerson I didn't see those changes uploaded to the github, just saw your message on this, I made the same changes myself and pushed a new version to the chef server and updated the ckan instances.  

Any user is now able to create groups and organizations.
